todizzle/urls.py
from django.conf.urls import url
from django.contrib import admin
from todos import views

urlpatterns = [
    url(r'^$', views.HomeView.as_view(), name='home'),
    
    url(r'^item/(\d+)$', views.item_page, name="item"),
    url(r'^item/(\d+)/complete', views.item_complete, name='item_complete'),
    url(r'^item/(\d+)/archive', views.item_archive, name='item_archive'),
    url(r'^item/(\d+)/delete', views.item_delete, name='item_delete'),
    
    url(r'^tags$', views.TagsView.as_view(), name='tags_view'),
    url(r'^tag/(\d+)$', views.tag_view, name='tag_view'),
    
    url(r'^admin/', admin.site.urls),
]

todos/models.py
from django.db import models
from django.utils import timezone
from django.template.defaultfilters import default


class Tag(models.Model):
    created = models.DateTimeField(default=timezone.now, blank=True)
    name = models.TextField(null=True, blank=True)
    
    def __str__(self):
        return self.name

    def friendly_created_date(self):        
        created = self.created

        return created.strftime('%B %d, %Y, %I:%M %p')

class Item(models.Model):
    created = models.DateTimeField(default=timezone.now, blank=True)
    updated = models.DateTimeField(auto_now=True, null=True)
    text = models.TextField(default='')
    tags = models.ManyToManyField(Tag, blank=True, null=True)
    due_date = models.DateTimeField(blank=True, null=True)
    completed = models.BooleanField(default=False)
    completed_date = models.DateTimeField(blank=True, null=True)
    archived = models.BooleanField(default=False) 
    
    def __str__(self):
        return self.text

    def friendly_created_date(self):        
        created = self.created

        return created.strftime('%B %d, %Y, %I:%M %p')
    
    def friendly_due_date(self):
        due_date = timezone.localtime(self.due_date)
        
        return due_date.strftime('%B %d, %Y, %I:%M %p')

    def friendly_completed_date(self):
        completed_date = self.completed_date
        
        return completed_date.strftime('%B %d, %Y, %I:%M %p')   
    

todos/views.py
from django.shortcuts import redirect, render
from django.views import generic
from django.utils import timezone

from todos.models import Item, Tag
from todos.forms import TagForm

import datetime


class HomeView(generic.View):
    def get(self, request):
        items = Item.objects.all().filter(archived=False).order_by('-created')
        
        return render(request, 'home.html', { 'items': items })
    
    def post(self, request, *args, **kwargs):
        Item.objects.create(text=request.POST['item_text'])
        
        return redirect('/')


def item_page(request, item_pk):
    item = Item.objects.get(pk=item_pk)
    
    if item.tags:
        tags = []
        for tag in item.tags.all():
            tags.append(tag.name)
        
        tags = ','.join(tags)
    else:
        tags = ''
        
    if request.method == 'POST':
        due_date = request.POST['due_date']
        if due_date != '':
            item.due_date = datetime.datetime.strptime(due_date, '%m/%d/%Y %I:%M %p') # (10/29/2015 12:00 AM) 
        
        raw_tags = "".join(request.POST['tags'].lower().split())
        if len(raw_tags) > 0:
            tags_list = []
            for raw_tag in raw_tags.split(","):
                tag, created = Tag.objects.get_or_create(name=raw_tag)
                tags_list.append(tag)
            item.tags.add(*tags_list) 
        
        item.save()
        
        return redirect('/')
    
    return render(request, 'item.html', { 'item': item, 'tags': tags })
    
def item_complete(request, item_pk): 
    item = Item.objects.get(pk=item_pk)
    timezone.activate("America/Los_Angeles")
    item.completed_date = timezone.now()
    item.completed = True
    item.save()
    
    return render(request, 'home.html')
    
def item_archive(request, item_pk):
    item = Item.objects.get(pk=item_pk)
    item.archived = True
    item.save()
    
def item_delete(request, item_pk):
    item = Item.objects.get(pk=item_pk)
    item.delete()


class TagsView(generic.ListView):
    template_name = 'tags.html'
    context_object_name = 'tags'
    
    def get_queryset(self):
        return Tag.objects.all().order_by('name')
    
   
def tag_view(request, tag_pk):
    tag = Tag.objects.get(pk=tag_pk)
    items = Item.objects.filter(tags=tag).filter(archived=False).order_by('-created')
    
    if request.method == 'POST':
        item = Item.objects.create(text=request.POST['item_text'])
        item.tags.add(tag)
        
        return redirect('tag_view', tag.pk)
    
    return render(request, 'tag.html', { 'tag': tag, 'items': items })

todos/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta name="description" content="">
	    <meta name="author" content="">
	    <link rel="shortcut icon" href="{% static 'static/images/favicon.ico' %}" />
		<title>Todizzle | {% block title %}{% endblock title %}</title>
		
		<!-- Bootstrap -->
		<link href="{% static 'bootstrap/css/bootstrap.css' %}" rel="stylesheet">
		
		<!-- Font-awesome -->
		<link href="{% static 'font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
		
		<!-- Custom styles for this template -->
	    <link href="{% static 'bootstrap/css/dashboard.css' %}" rel="stylesheet" type="text/css" />
	    
	    <link href="{% static 'custom.css' %}" rel="stylesheet" type="text/css" />
		
		<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
		<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
		<!--[if lt IE 9]>
			<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
			<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
		<![endif]-->
		
		<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
		<script src="{% static 'js/jquery.min.js' %}"></script>
		<!-- Include all compiled plugins (below), or include individual files as needed -->
		<script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
		
		<!-- dataTables css -->
		<link href="{% static 'css/dataTables.bootstrap.min.css' %}" rel="stylesheet">
		
	    <!-- dataTables js -->
	    <script src="{% static 'js/jquery.dataTables.min.js' %}"></script>
		<script src="{% static 'js/dataTables.bootstrap.min.js' %}"></script>
	    
		<!-- Bootstrap datetimepicker -->
	    <link href="{% static 'css/bootstrap-datetimepicker.min.css' %}" rel="stylesheet" type="text/css" />
	    <script src="{% static 'js/moment.min.js' %}"></script>
	    <script src="{% static 'js/moment-with-locales.min.js' %}"></script>
		<script src="{% static 'js/bootstrap-datetimepicker.min.js' %}"></script>	    
	    
	    <!-- Bootstrap Tags Input  -->
	    <link href="{% static 'css/bootstrap-tagsinput.css' %}" rel="stylesheet" type="text/css" />
	    <script src="{% static 'js/bootstrap-tagsinput.js' %}"></script>
	    
	    <!-- d3.js -->
	    <script src="{% static 'js/d3.min.js' %}" charset="utf-8"></script>
		
		{% block head %}{% endblock head %}
	</head>
	<body>
		{% block body %}
			<nav class="navbar navbar-inverse navbar-fixed-top">
				<div class="container-fluid">
					<div class="navbar-header">
						<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
							<span class="sr-only">Toggle navigation</span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
						</button>
						<a class="navbar-brand" href="/">Todizzle</a>
					</div>
					<div id="navbar" class="navbar-collapse collapse">
						<ul class="nav navbar-nav navbar-right">
							{% block nav %}{% endblock nav %}
						</ul>						
					</div>
				</div>
			</nav>			
			<div class="container-fluid">
				{% block container %}
					{% block pageheaders %}{% endblock pageheaders %}
					{% block alerts %}{% endblock alerts %}
				{% endblock container %}
			</div>
		{% endblock body %}
	</body>
</html>

todos/templates/home.html
{% extends 'base.html' %}
{% block title %}List{% endblock title %}
{% block head %}
	<script>		
		$(document).ready(function() {
		    var table = $('#todo').DataTable({
		    	"columnDefs": [
		    		{ "type": "datetime-moment", targets: 4 },
		    		{ "orderable": false, "targets": 4 }
		    	]
		    });
		    
		    function get_pk(event){
		    	var target = $(event.target);
		    	var item_pk = target.attr('data-item-pk');
		    	return item_pk;
		    }
		    
		    $('.glyphicon-ok').click(function(event) {
		    	var item_pk = get_pk(event);   	
		    	$.ajax({
		    		url : "/item/" + item_pk + "/complete",
		    		type : 'get'
		    	});
		    });		    
		    
		    $('.glyphicon-remove').click(function (event){
		    	var item_pk = get_pk(event);
		    	var deleted = confirm('The item will be permanently deleted. Are you sure you want to delete this item?');
		    	if (deleted) {
			    	$.ajax({
			    		url : "/item/" + item_pk + "/delete",
			    		type : 'get'
			    	});		    		
		    	} 
		    } );
		    
		    $('.glyphicon-circle-arrow-down').click(function (event){
		    	var item_pk = get_pk(event);
		    	var archived = confirm('The item will be removed from your to-do list. Are you sure you want to archive this item?');
		    	if (archived) {
			    	$.ajax({
			    		url : "/item/" + item_pk + "/archive",
			    		type : 'get'
			    	});		    		
		    	}
		    	
		    });
		    
		} );				
	</script>
{% endblock head %}
{% block nav %}
	<li><a href="{% url 'tags_view' %}" title="">Tags</a></li>
	<li class="active"><a href="{% url 'home' %}" title="">Home</a></li>	
{% endblock nav %}
{% block container %}
	<div class="row">
		<div class="col-sm-12 col-md-12 main">
			{% block pageheaders %}
				<h1 class="page-header">To-dos</h1>						
			{% endblock pageheaders %}
			{% block alerts %}{% endblock alerts %}
		</div>
	</div>	
	<div class="row">
		<div class="col-sm-12 col-md-12 main">	
	        <form method="POST">
	        	{% csrf_token %}
	        	<div class="form-group">
		        	<label for="id_new_item">New item:</label>
		            <input type="text" name="item_text" class="form-control" id="id_new_item" placeholder="Enter a to-do item" />
	            </div>	            
	        </form>
	        <div class="table-responsive">
		        <table class="table table-condensed" id="todo">
		        	<thead>
		        		<tr>
		        			<th>#</th>
		        			<th>Item</th>
		        			<th>Tags</th>
		        			<th>Due</th>
		        			<th>Actions</th>
		        		</tr>
		        	</thead>
		        	<tbody>
			            {% for item in items %}
			            	{% if  item.friendly_completed_date != None %}
			                	<tr class="completed">
			                {% else %}
			                	<tr>		                	
			                {% endif %}
			                
			                	<td>{{ forloop.counter }}</td>
			                	<td><a href="{% url 'item' item.pk %}">{{ item.text }}</a></td>	                	
			                	<td>
									{% for tag in item.tags.all %}
										<a href="{% url 'tag_view' tag.pk %}"><span class="badge">{{ tag.name }}</span></a>
									{% endfor %}	                	
			                	</td>
			                	{% if item.due_date %}
			                		<td>{{ item.friendly_due_date }}</td>
			                	{% else %}
			                		<td></td>
			                	{% endif %}
			                	<td>
			                		<span class="glyphicon glyphicon-ok" data-item-pk="{{ item.pk }}" aria-hidden="true" title="complete"></span>
			                		<span class="glyphicon glyphicon-remove" data-item-pk="{{ item.pk }}" aria-hidden="true" title="delete"></span>
			                		<span class="glyphicon glyphicon-circle-arrow-down" data-item-pk="{{ item.pk }}" aria-hidden="true" title="archive"></span>
			                	</td>			                	
			                </tr>
			            {% endfor %}
		            </tbody>
		        </table>
	        </div>			
		</div>
	</div>	
{% endblock container %}

todos/templates/item.html
{% extends 'base.html' %}
{% block title %}Item{% endblock title %}
{% block head %}
	<style>
		.bootstrap-tagsinput {
			width: 100%;
		}
	</style>
{% endblock head %}
{% block nav %}
	<li><a href="{% url 'tags_view' %}" title="">Tags</a></li>
	<li><a href="{% url 'home' %}" title="">Home</a></li>	
{% endblock nav %}
{% block container %}
	<div class="row">
		<div class="col-sm-12 col-md-12 main">
			{% block pageheaders %}
				<h1 class="page-header">{{ item.text }}</h1>								
			{% endblock pageheaders %}
			{% block alerts %}{% endblock alerts %}
			<div class="col-md-4"><span class="glyphicon glyphicon-calendar"></span> Created: <span class="badge">{{ item.created }}</span></div>
			<div class="col-md-4"><span class="glyphicon glyphicon-calendar"></span> Updated: <span class="badge">{{ item.updated }}</span></div>
			<div class="col-md-4"><span class="glyphicon glyphicon-calendar"></span> Completed: <span class="badge">{{ item.completed_date }}</span></div>	
		</div>
	</div>	
	<div class="row">
		<div class="col-sm-12 col-md-12 main">
		
			<form class="form-horizontal" method="POST">
				{% csrf_token %}
				<div class="form-group">
					<label for="id_due_date" class="col-sm-2 control-label">Due date:</label>
					<div class="col-sm-10">
						<div class='input-group date' id='datetimepicker1'>
							<input type='text' class="form-control" id="id_due_date" name="due_date"  />
							<span class="input-group-addon">
								<span class="glyphicon glyphicon-calendar"></span>
							</span>
						</div>
						<script type="text/javascript">
						    $(function () {
						    	var due_date = "{{ item.due_date }}";						
						    	if (due_date !== "None") {						    
						    		due_date = moment(moment(due_date, "MMMM DD, YYYY, hh:mm a.")).format('MM/DD/YYYY h:mm A');
							        
							        $('#datetimepicker1').datetimepicker({
							        	defaultDate: due_date
							        });								        
						    	} else {
						    		$('#datetimepicker1').datetimepicker();
						    	}						    						        
						    });
						</script>
					</div>				
				</div>
				<div class="form-group">
					<label for="id_tags" class="col-sm-2 control-label">Tags:</label>
					
					<div class="col-sm-10">
						<input class="form-control" id="id_tags" name="tags" type="text" value="{{ tags }}" data-role="tagsinput" >
					</div>
				</div>
				<div class="form-group">
					<div class="col-sm-offset-2 col-sm-10">
						<button type="submit" class="btn btn-success">Save</button>
					</div>
				</div>				
			</form>			           	
		</div>
	</div>	
	
{% endblock container %}

todos/templates/tag.html
{% extends 'base.html' %}
{% block title %} Tag: {{ tag.name }} {% endblock title %}
{% block head %}
	<script>		
		$(document).ready(function() {
		    var table = $('#todo').DataTable({
		    	"columnDefs": [
		    		{ "type": "datetime-moment", targets: 4 },
		    		{ "orderable": false, "targets": 4 }
		    	]
		    });
		    
		    function get_pk(event){
		    	var target = $(event.target);
		    	var item_pk = target.attr('data-item-pk');
		    	return item_pk;
		    }
		    
		    $('.glyphicon-ok').click(function(event) {
		    	var item_pk = get_pk(event);   	
		    	$.ajax({
		    		url : "/item/" + item_pk + "/complete",
		    		type : 'get'
		    	});
		    });		    
		    
		    $('.glyphicon-remove').click(function (event){
		    	var item_pk = get_pk(event);
		    	var deleted = confirm('The item will be permanently deleted. Are you sure you want to delete this item?');
		    	if (deleted) {
			    	$.ajax({
			    		url : "/item/" + item_pk + "/delete",
			    		type : 'get'
			    	});		    		
		    	} 
		    } );
		    
		    $('.glyphicon-circle-arrow-down').click(function (event){
		    	var item_pk = get_pk(event);
		    	var archived = confirm('The item will be removed from your to-do list. Are you sure you want to archive this item?');
		    	if (archived) {
			    	$.ajax({
			    		url : "/item/" + item_pk + "/archive",
			    		type : 'get'
			    	});		    		
		    	}
		    	
		    });
		    
		} );				
	</script>
{% endblock head %}
{% block nav %}
	<li class="active"><a href="{% url 'tags_view' %}" title="">Tags</a></li>
	<li><a href="{% url 'home' %}" title="">Home</a></li>	
{% endblock nav %}
{% block container %}
	<div class="row">
		<div class="col-sm-12 col-md-12 main">
			{% block pageheaders %}
				<h1 class="page-header">Tag: {{ tag.name }}</h1>						
			{% endblock pageheaders %}
			{% block alerts %}{% endblock alerts %}
		</div>
	</div>	
	<div class="row">
		<div class="col-sm-12 col-md-12 main">	
	        <form method="POST">
	        	{% csrf_token %} 	
	        	<div class="form-group">
		        	<label for="id_new_item">New item:</label>
		            <input type="text" name="item_text" class="form-control" id="id_new_item" placeholder="Enter a to-do item" />
	            </div>	            
	        </form>
	        <div class="table-responsive">
		        <table class="table table-condensed" id="todo">
		        	<thead>
		        		<tr>
		        			<th>#</th>
		        			<th>Item</th>
		        			<th>Tags</th>
		        			<th>Due</th>
		        			<th>Actions</th>
		        		</tr>
		        	</thead>
		        	<tbody>
			            {% for item in items %}
			            	{% if  item.friendly_completed_date != None %}
			                	<tr class="completed">
			                {% else %}
			                	<tr>		                	
			                {% endif %}
			                
			                	<td>{{ forloop.counter }}</td>
			                	<td><a href="{% url 'item' item.pk %}">{{ item.text }}</a></td>	                	
			                	<td>
									{% for tag in item.tags.all %}
										<a href="{% url 'tag_view' tag.pk %}"><span class="badge">{{ tag.name }}</span></a>
									{% endfor %}	                	
			                	</td>
			                	{% if item.due_date %}
			                		<td>{{ item.friendly_due_date }}</td>
			                	{% else %}
			                		<td></td>
			                	{% endif %}
			                	<td>
			                		<span class="glyphicon glyphicon-ok" data-item-pk="{{ item.pk }}" aria-hidden="true" title="complete"></span>
			                		<span class="glyphicon glyphicon-remove" data-item-pk="{{ item.pk }}" aria-hidden="true" title="delete"></span>
			                		<span class="glyphicon glyphicon-circle-arrow-down" data-item-pk="{{ item.pk }}" aria-hidden="true" title="archive"></span>
			                	</td>			                	
			                </tr>
			            {% endfor %}
		            </tbody>
		        </table>
	        </div>			
		</div>
	</div>	
{% endblock container %}

todos/templates/tags.html
{% extends 'base.html' %}
{% block title %}Tags{% endblock title %}
{% block head %}
	<script>
		$(document).ready(function() {
		    var table = $('#tags').DataTable({
		    	"columnDefs": [
		    		{ "type": "datetime-moment", targets: 1 }		    		
		    	]
		    });	    
		});		
	</script>
{% endblock head %}
{% block nav %}
	<li class="active"><a href="{% url 'tags_view' %}" title="">Tags</a></li>
	<li><a href="{% url 'home' %}" title="">Home</a></li>	
{% endblock nav %}
{% block container %}
	<div class="row">
		<div class="col-sm-12 col-md-12 main">
			{% block pageheaders %}
				<h1 class="page-header">Tags</h1>						
			{% endblock pageheaders %}
			{% block alerts %}{% endblock alerts %}
		</div>
	</div>	
	<div class="row">
		<div class="col-sm-12 col-md-12 main">	
	        <div class="table-responsive">
		        <table class="table table-condensed" id="tags">
		        	<thead>
		        		<tr>
		        			<th>Tag</th>
		        			<th>Created</th>
		        		</tr>
		        	</thead>
		        	<tbody>
		        		{% if tags %}		        			
		        			{% for tag in tags %}
		        				<tr>
		        					<td><a href="{% url 'tag_view' tag.pk %}">{{ tag.name }}</a></td>
		        					<td>{{ tag.friendly_created_date }}</td>
		        				</tr>
		        			{% endfor %}
		        		{% else %}
		        			<tr><td>No tags exist yet.</td></tr>
		        		{% endif %}		   			          
		            </tbody>
		        </table>
	        </div>			
		</div>
	</div>	
{% endblock container %}